name: Linux (OpenGL)

on:
  push:
    branches:
    - v3
  pull_request:
    branches:
    - v3

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Apt Update
      run: sudo apt update
    - name: Apt Install
      run: sudo apt-get install libasound2-dev libxinerama-dev libxrandr-dev libgl1-mesa-dev libxi-dev libxcursor-dev libudev-dev libwayland-dev wayland-protocols libxkbcommon-dev ninja-build imagemagick xvfb --yes --quiet

    - name: Get Submodules
      run: ./get_dlc

    - name: Compile shader
      working-directory: shader
      run: ../kore/make linux -g opengl --debug --option screenshot --compile
    - name: Run shader
      working-directory: shader/deployment
      run: xvfb-run ../build/debug/shader
    - name: Check shader
      working-directory: shader
      run: compare-im6 -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  shader failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: shader image
        path: shader/Deployment/test.png
