name: Windows (Direct3D 12)

on:
  push:
    branches:
    - v3
  pull_request:
    branches:
    - v3

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4


    - name: Install WARP 1.0.13
      run: nuget install Microsoft.Direct3D.WARP
    - name: Get Submodules
      run: ./get_dlc

    - name: Copy WARP
      working-directory: 00_empty
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 00_empty
      working-directory: 00_empty
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 00_empty
      working-directory: 00_empty
      run: magick compare -metric mae ./reference.png ./deployment/test.png difference.png
    - name: Upload  00_empty failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 00_empty image
        path: 00_empty/Deployment/test.png
    - name: Copy WARP
      working-directory: 01_triangle
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 01_triangle
      working-directory: 01_triangle
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 01_triangle
      working-directory: 01_triangle
      run: magick compare -metric mae ./reference.png ./deployment/test.png difference.png
    - name: Upload  01_triangle failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 01_triangle image
        path: 01_triangle/Deployment/test.png
    - name: Copy WARP
      working-directory: 02_matrix
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 02_matrix
      working-directory: 02_matrix
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 02_matrix
      working-directory: 02_matrix
      run: magick compare -metric mae ./reference.png ./deployment/test.png difference.png
    - name: Upload  02_matrix failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 02_matrix image
        path: 02_matrix/Deployment/test.png
    - name: Copy WARP
      working-directory: 03_colored_cube
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 03_colored_cube
      working-directory: 03_colored_cube
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 03_colored_cube
      working-directory: 03_colored_cube
      run: magick compare -metric mae ./reference.png ./deployment/test.png difference.png
    - name: Upload  03_colored_cube failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 03_colored_cube image
        path: 03_colored_cube/Deployment/test.png
    - name: Copy WARP
      working-directory: 04_textured_cube
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 04_textured_cube
      working-directory: 04_textured_cube
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 04_textured_cube
      working-directory: 04_textured_cube
      run: magick compare -metric mae ./reference.png ./deployment/test.png difference.png
    - name: Upload  04_textured_cube failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 04_textured_cube image
        path: 04_textured_cube/Deployment/test.png
    - name: Copy WARP
      working-directory: 05_camera_controls
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 05_camera_controls
      working-directory: 05_camera_controls
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check 05_camera_controls
      working-directory: 05_camera_controls
      run: magick compare -metric mae ./reference.png ./deployment/test.png difference.png
    - name: Upload  05_camera_controls failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 05_camera_controls image
        path: 05_camera_controls/Deployment/test.png
    - name: Copy WARP
      working-directory: shader
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile shader
      working-directory: shader
      run: ../kore/make windows -v vs2022 -g direct3d12 --debug --option screenshot --run
    - name: Check shader
      working-directory: shader
      run: magick compare -metric mae ./reference.png ./deployment/test.png difference.png
    - name: Upload  shader failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: shader image
        path: shader/Deployment/test.png
