name: Windows (Direct3D 12)

on:
  push:
    branches:
    - v3
  pull_request:
    branches:
    - v3

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4


    - name: Install WARP 1.0.13
      run: nuget install Microsoft.Direct3D.WARP
    - name: Get Submodules
      run: ./get_dlc

    - name: Copy WARP
      working-directory: 00_empty
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 00_empty
      working-directory: 00_empty
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check 00_empty
      working-directory: 00_empty
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  00_empty failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 00_empty image
        path: 00_empty/Deployment/test.png
    - name: Copy WARP
      working-directory: 01_triangle
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 01_triangle
      working-directory: 01_triangle
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check 01_triangle
      working-directory: 01_triangle
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  01_triangle failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 01_triangle image
        path: 01_triangle/Deployment/test.png
    - name: Copy WARP
      working-directory: 02_matrix
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 02_matrix
      working-directory: 02_matrix
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check 02_matrix
      working-directory: 02_matrix
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  02_matrix failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 02_matrix image
        path: 02_matrix/Deployment/test.png
    - name: Copy WARP
      working-directory: 03_colored_cube
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 03_colored_cube
      working-directory: 03_colored_cube
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check 03_colored_cube
      working-directory: 03_colored_cube
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  03_colored_cube failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 03_colored_cube image
        path: 03_colored_cube/Deployment/test.png
    - name: Copy WARP
      working-directory: 04_textured_cube
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 04_textured_cube
      working-directory: 04_textured_cube
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check 04_textured_cube
      working-directory: 04_textured_cube
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  04_textured_cube failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 04_textured_cube image
        path: 04_textured_cube/Deployment/test.png
    - name: Copy WARP
      working-directory: 05_camera_controls
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 05_camera_controls
      working-directory: 05_camera_controls
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check 05_camera_controls
      working-directory: 05_camera_controls
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  05_camera_controls failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 05_camera_controls image
        path: 05_camera_controls/Deployment/test.png
    - name: Copy WARP
      working-directory: 06_render_targets
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 06_render_targets
      working-directory: 06_render_targets
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check 06_render_targets
      working-directory: 06_render_targets
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  06_render_targets failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 06_render_targets image
        path: 06_render_targets/Deployment/test.png
    - name: Copy WARP
      working-directory: 07_multiple_render_targets
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 07_multiple_render_targets
      working-directory: 07_multiple_render_targets
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check 07_multiple_render_targets
      working-directory: 07_multiple_render_targets
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  07_multiple_render_targets failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 07_multiple_render_targets image
        path: 07_multiple_render_targets/Deployment/test.png
    - name: Copy WARP
      working-directory: 08_float_render_targets
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 08_float_render_targets
      working-directory: 08_float_render_targets
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check 08_float_render_targets
      working-directory: 08_float_render_targets
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  08_float_render_targets failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 08_float_render_targets image
        path: 08_float_render_targets/Deployment/test.png
    - name: Copy WARP
      working-directory: 09_depth_render_targets
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 09_depth_render_targets
      working-directory: 09_depth_render_targets
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check 09_depth_render_targets
      working-directory: 09_depth_render_targets
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  09_depth_render_targets failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 09_depth_render_targets image
        path: 09_depth_render_targets/Deployment/test.png
    - name: Copy WARP
      working-directory: 10_cubemap
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 10_cubemap
      working-directory: 10_cubemap
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check 10_cubemap
      working-directory: 10_cubemap
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  10_cubemap failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 10_cubemap image
        path: 10_cubemap/Deployment/test.png
    - name: Copy WARP
      working-directory: 11_instanced_rendering
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 11_instanced_rendering
      working-directory: 11_instanced_rendering
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check 11_instanced_rendering
      working-directory: 11_instanced_rendering
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  11_instanced_rendering failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 11_instanced_rendering image
        path: 11_instanced_rendering/Deployment/test.png
    - name: Copy WARP
      working-directory: 12_set_render_target_depth
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 12_set_render_target_depth
      working-directory: 12_set_render_target_depth
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check 12_set_render_target_depth
      working-directory: 12_set_render_target_depth
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  12_set_render_target_depth failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 12_set_render_target_depth image
        path: 12_set_render_target_depth/Deployment/test.png
    - name: Copy WARP
      working-directory: 13_generate_mipmaps
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 13_generate_mipmaps
      working-directory: 13_generate_mipmaps
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check 13_generate_mipmaps
      working-directory: 13_generate_mipmaps
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  13_generate_mipmaps failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 13_generate_mipmaps image
        path: 13_generate_mipmaps/Deployment/test.png
    - name: Copy WARP
      working-directory: 14_set_mipmap
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 14_set_mipmap
      working-directory: 14_set_mipmap
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check 14_set_mipmap
      working-directory: 14_set_mipmap
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  14_set_mipmap failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 14_set_mipmap image
        path: 14_set_mipmap/Deployment/test.png
    - name: Copy WARP
      working-directory: 15_deinterleaved_buffers
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile 15_deinterleaved_buffers
      working-directory: 15_deinterleaved_buffers
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check 15_deinterleaved_buffers
      working-directory: 15_deinterleaved_buffers
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  15_deinterleaved_buffers failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: 15_deinterleaved_buffers image
        path: 15_deinterleaved_buffers/Deployment/test.png
    - name: Copy WARP
      working-directory: shader
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile shader
      working-directory: shader
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check shader
      working-directory: shader
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  shader failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: shader image
        path: shader/Deployment/test.png
    - name: Copy WARP
      working-directory: texture
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile texture
      working-directory: texture
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check texture
      working-directory: texture
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  texture failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: texture image
        path: texture/Deployment/test.png
    - name: Copy WARP
      working-directory: computeshader
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile computeshader
      working-directory: computeshader
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check computeshader
      working-directory: computeshader
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  computeshader failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: computeshader image
        path: computeshader/Deployment/test.png
    - name: Copy WARP
      working-directory: texturearray
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile texturearray
      working-directory: texturearray
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check texturearray
      working-directory: texturearray
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  texturearray failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: texturearray image
        path: texturearray/Deployment/test.png
    - name: Copy WARP
      working-directory: raytracing
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile raytracing
      working-directory: raytracing
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check raytracing
      working-directory: raytracing
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  raytracing failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: raytracing image
        path: raytracing/Deployment/test.png
    - name: Copy WARP
      working-directory: bindless
      run: echo F|xcopy D:\a\Kore-Samples\Kore-Samples\Microsoft.Direct3D.WARP.1.0.13\build\native\bin\x64\d3d10warp.dll Deployment\d3d10warp.dll
    - name: Compile bindless
      working-directory: bindless
      run: ../Kinc/make windows -v vs2022 -g direct3d12 --option screenshot --debug --run
    - name: Check bindless
      working-directory: bindless
      run: magick compare -metric mae .\reference.png .\Deployment\test.png difference.png
    - name: Upload  bindless failure image
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: bindless image
        path: bindless/Deployment/test.png
